from . import woocommerce_instance_integration
from . import woocommerce_log
from . import woocommerce_payment_gateway
from . import woocommerce_shipping_method
from . import customer_data_queue
from . import res_partner
from . import woocommerce_product_category
from . import woocommerce_product_tags
from . import woocommerce_order_data_queue
from . import sale_order
from . import woocommerce_financial_status_configuration
from . import woocommerce_order_workflow_automation
from . import delivery_carrier
from . import woocommerece_product_data_queue
from . import woocommerce_product_listing
from . import woocommerce_product_listing_item
from . import product_pricelist
from . import woocommerce_product_image
from . import woocommerce_inventory_data_queue
from . import ir_cron
from . import product_template
from . import woocommerce_webhook
from . import woocommerce_taxes
from . import account_tax
from . import account_move
